versatus/lasr

crates/actors/Cargo.toml, crates/cli/Cargo.toml, crates/clients/Cargo.toml, crates/compute/Cargo.toml, crates/contract/Cargo.toml, crates/messages/Cargo.toml, crates/node/Cargo.toml, crates/rpc/Cargo.toml, crates/types/Cargo.toml, crates/wallet/Cargo.toml
Setting version number for versatus repo and lasr repo to match beta release. Will tag main once merged unless there are other specific changes coming.
=> Set beta version number in Cargo.toml

crates/types/src/programming_model.rs
Adds docs for types in the `programming_model` module. Also clears up warnings from cargo & formatting.
=> Add documentation to programming model types

crates/actors/Cargo.toml, crates/actors/src/validator.rs
Potential cause for the core dump being the thread count is initialized as a hard-coded 50 threads. This just changes it to use the number of logical cores instead. We should consider the overall overhead and potential consequences of using multiple `rayon::ThreadPool`s at runtime in general, but this will at least reduce the chance of things failing due to an uninitialized thread pool.
Ref #98
=> Change hard-coded thread count to `num_cpus::get()`

Cargo.lock, crates/actors/src/batcher.rs, crates/actors/src/helpers.rs, crates/node/Cargo.toml, crates/node/src/main.rs
Updates the `helpers` module with some convenience types and a trait extension for `ractor::Actor` to make integrating the new async design pattern easier for the other `Actor` types.
This implements the use of the aforementioned trait and types for the `BatcherActor` and fixes the error handling for failed transaction methods (prev `handle_batcher_error`)
Ref #71
=> Add `ActorExt` & `Batcher::handle_transaction_error`

crates/actors/src/batcher.rs, crates/node/src/main.rs
Ref #132 
Attempts to alleviate the failure to acquire the `DaClient` actor from the `ractor` registry. This will rule out the possibility that the `JoinHandle` is dropped, which would remove the actor from the registry.
=> Make actor `JoinHandle`s persist the life of the program, add log for `GetNextBatch`

crates/actors/src/validator.rs, crates/node/src/main.rs
Ref #71 
Renames `Validator` to `ValidatorActor`. Slight refactor to the `ractor::Actor` impl for `ValidatorActor` to use the `ValidatorCore` that's instantiated in the `main` function, this will also reuse the same data instead of creating a new default `ValidatorCore` on `pre_start`. Implements `ActorExt` for `ValidatorActor` and adds a test to ensure its effectiveness. Updates `ValidatorError` to make error conversion easier in the abstracted `ValidatorActor` associated functions.
=> Add `ValidatorActor` to future handler

crates/actors/src/da_client.rs, crates/node/src/main.rs
Ref #71 
Refactor to the `ractor::Actor` impl for `DaClient`: Adds a `DaClientActor` type as the `Actor`, and uses `DaClient` as the `ractor::Actor::State`. Abstracts the message logic into associated functions on the `DaClientActor`. Implements `ActorExt` for `DaClientActor`.
=> Add `DaClientActor` to future handler

crates/actors/src/eo_server.rs, crates/node/src/main.rs
Ref #71 
While refactoring the `EoServer` to be added to the future handler, I realized the `async` functions that are called are unnecessary. This refactor just renames `EoServer` to `EoServerActor` and removes the unused async await points from the `ractor::Actor::handle` method. It also refactors methods that take `self` but do not use `self` into associated functions.
=> Remove unnecessary async await points in `EoServerActor`

crates/actors/src/eo_server.rs
Adding logs to see what response if any we get from Kaleido.
=> Add extra logs for `eo_server::run`

Cargo.lock, crates/actors/src/account_cache.rs, crates/actors/src/batcher.rs, crates/actors/src/manager.rs, crates/messages/Cargo.toml, crates/messages/src/messages.rs, crates/node/src/main.rs
Closes #169 
Closes #171 
Adds persistence read hooks to `account_cache`'s `handle()`
Abstracts client into `main()`
Creates an `inner` structure for `AccountCache`, which enables the actor to accept `tikv_client` while still deriving `Debug, Default`
=> Add read hooks for persistence layer

crates/actors/src/helpers.rs
Closes #172 
Removes time constraint for acquiring an account from the DA. The need for the timeout is outdated, this changes it to just wait for a response from the DA.
=> Remove timeout requirement for acquiring account from DA

Cargo.lock, crates/actors/Cargo.toml, crates/actors/src/engine.rs, crates/actors/src/eo_server.rs, crates/actors/src/helpers.rs, crates/actors/src/rpc_server.rs, crates/actors/src/scheduler.rs, crates/cli/Cargo.toml, crates/messages/Cargo.toml, crates/messages/src/messages.rs, crates/node/Cargo.toml, crates/node/src/main.rs, crates/rpc/Cargo.toml, crates/rpc/src/rpc.rs
Closes #189 
Bumps jsonrpsee dep to `0.22.5` and handles API changes.
Increases RPC server connection to `1000`, default was `100`.
This PR is ready, but
**BEFORE MERGE:**
This has been tested in regard to compilation, by setting the `internal_rpc` dependency to the branch mentioned above.
=> Bump `jsonrpsee` version & Server connection limit

crates/compute/src/compute.rs
Closes #107 
** This code hasn't been tested due to challenges with running `runsc` localy **
This code does the following:
1. Creates a temporary file based upon the container path and container id - ensures that file exists on disk - ensures the file is blank
2. Redirects the Command to execute `runsc` to dump its output to this temporary file
3. Reads the contents of the temporary file and returns them instead
4. Deletes the file after it has been used up
=> Read container output from temp file instead of Std Out

crates/actors/src/eo_server.rs
Catches a potential edge case where the `EoServerActor::run()` method will exit and stop checking the server for logs.
=> Reacquire `EoServerActor` after `ActorStatus::Stopped` in `EoServerActor::run()`

.github/workflows/rust.yml, Cargo.lock, crates/actors/Cargo.toml, crates/actors/src/account_cache.rs, crates/actors/src/batcher.rs, crates/actors/src/eo_server.rs, crates/actors/src/manager.rs, crates/actors/tests/account.rs, crates/compute/src/compute.rs, crates/messages/Cargo.toml, crates/messages/src/messages.rs, crates/node/Cargo.toml, crates/node/src/main.rs, crates/types/Cargo.toml, crates/types/src/account.rs, crates/types/src/lib.rs, crates/types/src/persistence.rs, crates/types/src/programming_model.rs, crates/types/src/token.rs, crates/types/src/transaction.rs
Closes #205 
Adds the tests necessary to prove events that update `Account` function as intended. Also adds the ability to test with in-memory key-value storage (`HashMap`) which relieves the overhead of needing a `tikv_client` running. The `MinimalNode` testing type can eventually be moved to its own module and expanded upon if needed, which makes testing node processes outside of RPC calls, IPFS and other compute related stuff (outside of the scope of these tests) relatively easy.
=> Add testing framework for events that update `Account`

crates/actors/src/batcher.rs
Ref #232 
Updates the error message for a failure to `put` an `Account` into persistence store.
=> Add helpful error message to account `put` method

crates/actors/Cargo.toml, crates/actors/src/engine.rs, crates/actors/src/executor.rs, crates/cli/Cargo.toml, crates/compute/Cargo.toml, crates/node/Cargo.toml, crates/node/src/main.rs
Closes #220 
Instead of using the `local` feature as default & as an off switch for the `remote` feature, removes the extra feature entirely.
Replacing the `local` feature calls with `#[cfg(not(feature = "remote"))]` handles the on/off of the `remote` feature without the need for the extra feature.
=> Rework `remote` & `local` features

.github/workflows/rust.yml
Closes #218 
Adds a check that the workspace compiles.
=> Add cargo build check to CI

crates/compute/src/compute.rs
Instead of using a string for the command, `"runsc"`, this will use the new environment variable or default path to a runsc binary.
=> Use runsc runtime path in `OciManager::run_container`

.gitignore, Cargo.lock, README.md, crates/actors/Cargo.toml, crates/cli/Cargo.toml, crates/cli/README.md, crates/compute/Cargo.toml, crates/contract/Cargo.toml, crates/eo_listener/Cargo.toml, crates/messages/Cargo.toml, crates/node/Cargo.toml, crates/node/README.md, crates/rpc/Cargo.toml, crates/types/Cargo.toml, crates/wallet/Cargo.toml, deny.toml, flake.lock, flake.nix, nixos/modules/deployments/README.md, nixos/modules/deployments/common/default.nix, nixos/modules/deployments/debug/debug-options.nix, nixos/modules/deployments/prod/prod-options.nix, nixos/overlay.nix
Part of https://github.com/versatus/versatus.nix/issues/49 which moves the repo-specific logic into its respective repo so that the versatus.nix flake can be used across the org as needed.
What this does:
- Moves the deployment process into the lasr repo from the versatus.nix repo
- Adds developer environment
- Adds checks for cargo licenses, advisories and sources (like crates.io)
- Updates READMEs where applicable
- Adds the potential for a github codespace for newcomers
- Overall increase to maintainability of the project, long term
=> Add `flake.nix`
