versatus/lasr

- Cargo.lock
- crates/actors/Cargo.toml
- crates/actors/src/batcher.rs
- crates/actors/src/da_client.rs
- crates/actors/src/engine.rs
- crates/actors/src/eo_server.rs
- crates/actors/src/executor.rs
- crates/actors/src/helpers.rs
- crates/actors/src/pending_transactions.rs
- crates/actors/src/rpc_server.rs
- crates/actors/src/scheduler.rs
- crates/actors/src/validator.rs
- crates/cli/src/cli.rs
- crates/compute/src/compute.rs
- crates/messages/src/messages.rs
- crates/node/src/main.rs
- crates/types/Cargo.toml
- crates/types/src/account.rs
- crates/types/src/programming_model.rs
- crates/types/src/signing.rs
- crates/types/src/token.rs
- crates/types/src/transaction.rs
- crates/wallet/src/wallet.rs
Contains a large amount of ad-hoc improvements and optimizations to stabilize LASR node protocol
> Stabilize LASR

- crates/actors/src/account_cache.rs
- crates/actors/src/batcher.rs
- crates/actors/src/blob_cache.rs
- crates/actors/src/da_client.rs
- crates/actors/src/engine.rs
- crates/actors/src/eo_server.rs
- crates/actors/src/executor.rs
- crates/actors/src/helpers.rs
- crates/actors/src/pending_transactions.rs
- crates/actors/src/rpc_server.rs
- crates/actors/src/scheduler.rs
- crates/actors/src/validator.rs
- crates/cli/src/cli.rs
- crates/clients/src/eo_client.rs
- crates/compute/src/compute.rs
- crates/compute/src/package.rs
- crates/messages/src/messages.rs
- crates/node/build.rs
- crates/node/src/main.rs
- crates/types/src/account.rs
- crates/types/src/programming_model.rs
- crates/types/src/signing.rs
- crates/types/src/token.rs
- crates/types/src/transaction.rs
- crates/wallet/src/wallet.rs
Ref #73 
removes redundancies in code base, impl default for various types, fix clippy errors
> Fix workspace clippy warnings

- crates/cli/src/cli.rs
> Add hex string value parsing to `U256Wrapper` `FromStr` implementation

- crates/actors/src/engine.rs
- crates/node/src/main.rs
Ref #71 
Slight refactor to `ractor::Actor` impl for `Engine`: Renames `Engine` to `EngineActor`. Abstracts logic for async messages into associated functions. Implements `ActorExt` for `EngineActor`, and adds a test for the `ractor::Actor::handle` method.
> Add `EngineActor` to future handler

- crates/actors/src/rpc_server.rs
Ref #71
While adding `LasrRpcServerActor` to the future handler, I found that the async await points were unnecessary. This PR just refactors the code to be synchronous and changes methods that take `self` but don't use `self` into associated functions.
> Remove unnecessary async await points from `LasrRpcServerActor`

- Cargo.lock
- crates/clients/Cargo.toml
- crates/clients/src/eo_client.rs
- crates/node/src/main.rs
Ref #71 
Abstracts message logic into associated functions on `EoClientActor`, implements `ActorExt` for `EoClientActor`, implements the future handler design pattern, and updates types in the `ractor::Actor` implementation for readability.
> Add `EoClientActor` to future handler

- crates/actors/src/da_client.rs
> Handle unwrap for `DaClient` actor

- crates/actors/src/eo_server.rs
- crates/node/src/main.rs
- entrypoints/pd.sh
- entrypoints/tikv.sh
- stack.yml
Adds logic to ensure that bridge filters are sorted properly given the update in the `EoServer` logic for acquiring logs from the Eo Contract
> Fix eo filter bug

- crates/actors/src/batcher.rs
- crates/actors/src/da_client.rs
> Make handle next batch request blocking 

- crates/actors/src/batcher.rs
> Use for loop, remove while let next

- crates/actors/src/helpers.rs
> Remove time constraint for acquiring blob index from EO

- crates/actors/src/eo_server.rs
> Add a 15s interval between `EoServer` block reads

- crates/actors/src/account_cache.rs
- crates/actors/src/batcher.rs
- crates/actors/src/blob_cache.rs
- crates/actors/src/da_client.rs
- crates/actors/src/engine.rs
- crates/actors/src/eo_client.rs
- crates/actors/src/eo_server.rs
- crates/actors/src/executor.rs
- crates/actors/src/helpers.rs
- crates/actors/src/pending_transactions.rs
- crates/actors/src/rpc_server.rs
- crates/actors/src/scheduler.rs
- crates/actors/src/validator.rs
> Add better logging for `ProcessGroupChanged` supervision event

- crates/actors/src/helpers.rs
Closes #176 
Remove DA logic from `get_account()`
Update logging & add notes
> Update `get_account()` method in `helpers.rs`

- crates/actors/src/account_cache.rs
- crates/actors/src/batcher.rs
- crates/actors/src/engine.rs
- crates/actors/src/eo_client.rs
- crates/actors/src/helpers.rs
- crates/actors/src/scheduler.rs
- crates/actors/src/validator.rs
- crates/messages/src/messages.rs
- crates/node/examples/tikv_account_example.rs
Closes #179 
Removed unused functions regarding the retrieval of `Account`'s via stale methods.
Updated logging to reflect changes
> Remove calls to get `Account` from DA & EO

- crates/actors/src/account_cache.rs
- crates/actors/src/batcher.rs
- crates/actors/src/engine.rs
- crates/actors/src/executor.rs
- crates/actors/src/helpers.rs
- crates/actors/src/scheduler.rs
- crates/actors/src/validator.rs
- crates/messages/src/messages.rs
- crates/node/src/main.rs
- crates/types/src/account.rs
Fixes persistence store reads and adds better logging around reads and writes to the account cache
> Use full hex String for persistence reads, add more robust logging

- crates/node/examples/README.md
- scripts/pd-server.sh
- scripts/tikv-server.sh
Closes #165 
Explains steps needed to get persistence store running for LASR.
> Add README.md for TiKV persistence store

- Cargo.lock
- crates/actors/src/validator.rs
- crates/types/src/programming_model.rs
While tracking down #194 
The logic in `ProgramUpdate` was hard to read and my LSP wasn't working so I did a bit of clean up. Should be much easier to verify now, pretty sure the problem lies elsewhere and just propagates to the error in the issue.
> Validator refactor from investigating #194

- crates/node/examples/tikv_account_example.rs
> Add E2E `account_type: Program()` example to `tikv_example`

- crates/actors/src/validator.rs
- crates/types/src/token.rs
Hello!
fixes #216
Please note that after deleting Balance(BalanceValue) from TokenFieldValue, I solved the compile error of crates/actors/src/validator.rs by deleting the associated branch. If you'd wish me to handle it differently, please don't hesitate to let me know. : )
Thanks for your time!
> Removed TokenFieldValue::Balance & TokenFieldValue::TokenIds from token.rs

- Cargo.lock
- Cargo.toml
- crates/actors/Cargo.toml
- crates/eo_listener/Cargo.toml
- crates/eo_listener/eo_contract_abi.json
- crates/eo_listener/src/lib.rs
- crates/eo_listener/src/main.rs
- crates/messages/Cargo.toml
- crates/node/Cargo.toml
For ease of access and convenience, moves `eo_listener` out of a separate repository.
> Move `eo_listener` repo into workspace

- crates/eo_listener/src/lib.rs
Bridge in event from block 376749 results in finding the event and resetting the filter to start at 376750
> fix: stop duplicate eo event detection

- Cargo.lock
- crates/actors/src/batcher.rs
- crates/compute/src/compute.rs
In search of the Batcher error we are running into on `lasr_vm`, added error handling to unhandled `Try` operator usage cases and supplied more descriptive error messages for any future debugging.
> Add error handling to OciManager

- crates/types/Cargo.toml
- crates/types/LICENSE.txt
- crates/types/README.md
> Setup `lasr_types` for `crates.io` publish

- crates/types/Cargo.toml
> Exclude `persistence.rs` from `lasr_types` crate

- crates/types/Cargo.toml
> Remove `persistence.rs` exclusion
